version: 2.1
jobs:
        build:
                docker:
                        - image: circleci/python:jessie
                steps:
                        - checkout
                        - run:
                                name: Install requirements
                                command: |
                                        pip install --upgrade --user pip
                                        pip install -r requirements.txt
                        - run:
                                name: Make test call to API
                                command: |
                                        python mailerlite-cli.py account info
