jobs:
        build:
                docker:
                        - image: circleci/python:jessie
                steps:
                        - checkout
                        - run:
                                name: Install requirements
                                command: |
                                        pip install --upgrade pip --user
                                        pip install -r requirements.txt
        test:
                docker:
                        - image: circleci/python:jessie
                steps:
                        - run:
                                name: Make test call to API
                                command: |
                                        python mailerlite-cli.py account info

workflows:
        version: 2
        build_and_test:
                jobs:
                        - build
                        - test:
                                requires:
                                        - build
