version: 2.1

orbs:
        python: circleci/python@0.3.0

jobs:
        build:
                executor: python/default
                steps:
                        - checkout
                        - python/load-cache
                        - python/install-deps
                        - python/save-cache
                        - run:
                                command: |
                                        mailerlite-cli.py account info
                                name: Test API conn
