version: 2.1
jobs:
        build_and_test:
                docker:
                        - image: circleci/python:jessie
                steps:
                        - checkout
                        - run:
                                name: Install requirements
                                command: |
                                        pip install --upgrade pip --user
                                        pip install -r requirements.txt
                        - run:
                                name: Make test call to API (accounts)
                                command: |
                                        python mailerlite-cli.py account info
                        - run:
                                name: Make test call to API (groups)
                                command: |
                                        python mailerlite-cli.py group list
