version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run: |
      pip install requirements.txt
  test:
    steps:
      - checkout
      - run:
          command: ./mailerlite-cli.py account info
          name: Test display account info

workflows:
  main:
    jobs:
      - build
      - test
