version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    docker: 'circleci/python:latest'
    steps:
      - checkout
      - run:
          command: ./mailerlite-cli.py account info
          name: Test call to mailerlite api

workflows:
  main:
    jobs:
      - build-and-test
